spring:
  datasource:
    password: password
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info